services:
  db:
    image: postgres:17-alpine
    container_name: pgadmin-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - pgadmin-net

  pgadmin:
    build: .
    container_name: pgadmin-web-dockerfile
    restart: unless-stopped
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - pgadmin-net

networks:
  pgadmin-net:

volumes:
  db_data:
  pgadmin_data:
